Add hm2
antonbugaets/RecomService pull request #2
Opened 2022-11-26 10:34 UTC by EgSergeenko

Add hm2 solution

2022-12-02 16:26 UTC, sharthZ23 requested changes
Есть следующие недочеты:
- По `UserKFoldPOut`
   - Проверьте на всем датасете, проблем в скорости быть не должно
   - У вас никак не учитывается параметр `p`
   - Нет проверки на соответствие разбиений условиям в задании
- По `pFound`
   - Нет сравнения с оригинальной версией. Нужно проверить как корректность, так и скорость работы

2022-12-05 04:20 UTC, kostya85 commented
Request approved

2022-12-05 06:20 UTC, antonbugaets commented
approved

2022-12-10 18:50 UTC, sharthZ23 approved these changes
Принимаю, 24 балла ставлю

2022-12-10 19:04 UTC, merged